=== Arobles912/lenguaje-de-marcas/XML/Ejercicio3Esquema/esquema3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="cancion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string" />
        <xs:element name="compositores" type="PatronCompositor" />
        <xs:element name="productores" type="PatronProductor" />
        <xs:element name="sello" type="xs:string" />
        <xs:element name="artista" type="xs:string" />
      </xs:sequence>
      <xs:attribute name="duracion" type="PatronDuracion"></xs:attribute>
      <xs:attribute name="año" type="xs:integer"></xs:attribute>
    </xs:complexType>
  </xs:element>
  
      <xs:complexType name="PatronCompositor">
      <xs:sequence>
       <xs:element name="compositor" type="PatronNombres"/>
      </xs:sequence>
    </xs:complexType>
    
          <xs:complexType name="PatronProductor">
      <xs:sequence>
       <xs:element name="productor" type="PatronNombres"/>
      </xs:sequence>
    </xs:complexType>
    
      <xs:complexType name="PatronNombres">
      <xs:sequence>
       <xs:element name="nombre" type="xs:string"/>
       <xs:element name="apellido" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
    
  <xs:simpleType name="PatronDuracion">
  <xs:restriction base="xs:string">
    <xs:pattern value="([\d{9}]+)*:([\d{9}]+)"/>
  </xs:restriction>
</xs:simpleType>
  
</xs:schema>

=== Arobles912/lenguaje-de-marcas/XML/Ejercicio3Esquema/ejercicio3esquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<cancion duracion="4:47" año="2008" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="esquema3.xsd">
<titulo>Give it 2 me</titulo>
<compositores>
<compositor>
<nombre>Pharrell</nombre>
<apellido>Williams</apellido>
</compositor>
</compositores>
<productores>
<productor>
<nombre>Pharrell</nombre>
<apellido>Williams</apellido>
</productor>
</productores>
<sello>Warner Bros. Records</sello>
<artista>Madonna</artista>
</cancion>
